#!/usr/bin/env python3
"""Claude Code PR review agent.

Usage:
    python review_pr.py --pr https://github.com/owner/repo/pull/123
    python review_pr.py --pr https://github.com/owner/repo/pull/123 --github-token ghp_xxx

Analyzes a PR diff and generates a structured review with:
- Summary, risks, suggestions, confidence score.
"""

import argparse
import json
import os
import re
import urllib.request
import urllib.error
from typing import Any


def fetch(url: str, token: str | None = None) -> Any:
    headers = {"Accept": "application/vnd.github.v3.diff"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        content = resp.read().decode()
    try:
        return json.loads(content)
    except (json.JSONDecodeError, UnicodeDecodeError):
        return content


def parse_pr_url(url: str) -> tuple[str, str, int]:
    m = re.match(r"https://github\.com/([^/]+)/([^/]+)/pull/(\d+)", url)
    if not m:
        raise ValueError(f"Invalid PR URL: {url}")
    return m.group(1), m.group(2), int(m.group(3))


def analyze_diff(diff: str) -> dict:
    if not diff:
        return {"summary": "No diff available.", "risks": [], "suggestions": [], "confidence": "Low"}

    files_changed = len(re.findall(r"^diff --git a/", diff, re.MULTILINE))
    lines_added = len(re.findall(r"^\+\+[^+]", diff, re.MULTILINE)) + len(re.findall(r"^\+[^+]", diff, re.MULTILINE))
    lines_removed = len(re.findall(r"^\-[^-]", diff, re.MULTILINE))

    risks = []
    suggestions = []
    summary_parts = []

    summary_parts.append(f"Changes {files_changed} file(s) (+{lines_added}/-{lines_removed} lines).")

    if re.search(r"(TODO|FIXME|HACK|XXX)\b", diff, re.IGNORECASE):
        risks.append("Contains TODO/FIXME markers that should be addressed before merge.")

    if re.search(r"console\.(log|debug|info|warn|error)\(", diff, re.IGNORECASE):
        risks.append("Debug console.log/console.error statements detected.")

    if re.search(r"(apiKey|secret|password|token|credential)\s*[:=]\s*[\"'][^\"']+[\"']", diff, re.IGNORECASE):
        risks.append("Potential hardcoded credential or API key detected.")

    if re.search(r"print\(", diff) and re.search(r"\.py$", diff):
        risks.append("Debug print() statements detected.")

    if re.search(r"def\s+test_|it\([\"']", diff, re.IGNORECASE):
        suggestions.append("Tests found — good coverage practice.")
    else:
        suggestions.append("No tests detected. Consider adding tests for the changes.")

    if re.search(r"except\s*:\s*$|except\s+Exception\s*:\s*$", diff, re.MULTILINE):
        risks.append("Bare except clause — catches all exceptions silently.")

    if len(diff) > 50000:
        suggestions.append("Very large diff. Consider splitting into smaller PRs for easier review.")

    confidence = "High" if len(risks) == 0 else "Medium" if len(risks) <= 2 else "Low"

    return {
        "summary": " ".join(summary_parts),
        "risks": risks,
        "suggestions": suggestions,
        "confidence": confidence,
    }


def format_review(result: dict, pr_url: str) -> str:
    lines = [f"## PR Review: {pr_url}", ""]
    lines.append("### Summary")
    lines.append(result["summary"])
    lines.append("")

    if result["risks"]:
        lines.append("### Identified Risks")
        for r in result["risks"]:
            lines.append(f"- ⚠️ {r}")
        lines.append("")

    if result["suggestions"]:
        lines.append("### Improvement Suggestions")
        for s in result["suggestions"]:
            lines.append(f"- 💡 {s}")
        lines.append("")

    lines.append(f"**Confidence Score**: {result['confidence']}")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by claude-review_")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Review a GitHub PR")
    parser.add_argument("--pr", required=True, help="PR URL (e.g., https://github.com/owner/repo/pull/123)")
    parser.add_argument("--github-token", help="GitHub token for private repos")
    args = parser.parse_args()

    token = args.github_token or os.environ.get("GITHUB_TOKEN")
    owner, repo, number = parse_pr_url(args.pr)

    diff_url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{number}"
    diff = fetch(diff_url, token)

    result = analyze_diff(diff)
    review = format_review(result, args.pr)
    print(review)


if __name__ == "__main__":
    main()
